package main.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    REQUEST_TYPE,
    UPDATE_MARK,
    UPDATE_PASSENGER,
    GETALL_USER,
    ADD_CLIENT,
    GET_CLIENT,
    GETALL_ACCOUNTS,
    GETALL_DEPOSITS,
    ADD_DEPOSIT,
    GETALL_CARDS,
    GET_CREDITS,
    AMOUNT_TRANSFER,
    AMOUNT_TRANSFER_CARD_ACCOUNT,
    AMOUNT_TRANSFER_ACCOUNT_CARD,
    AMOUNT_TRANSFER_ACCOUNT_ACCOUNT
}
